### PR TITLE
updates dependencies and reconfigures renovate config

### PR DESCRIPTION
**Pull request by AlanBreck**

### CODE REVIEW

**Comment by AlanBreck** [comment]
@bcaller and/or @thypon, am I clear to proceed with this PR despite the socket IO warnings (especially [this one](https://github.com/brave/store-brave-com/pull/49#issuecomment-1631493590))? I don't believe that we'll have an issue here since we don't save user input into the db, just data from Keystone (only accessible to Brave employees) and the Printful API.

**Comment by bcaller** [comment]
The "New, updated, and removed dependencies detected" does not have anything suspicious.

To be honest I also have trouble understanding what that "AI" warning about Prisma Migrate is referring to. As you mentioned, it's a package used by keystone for performing database migrations.

I'd ignore it.

**Comment by bcaller** [comment]
@SocketSecurity ignore @prisma/migrate@4.15.0

**Comment by AlanBreck** [comment]
@SocketSecurity ignore @prisma/migrate@4.15.0

**Pull request merged**
